<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Ngi trng xy t 80 nghn vin si</name>
   <tag></tag>
   <elementGuidId>82323db7-7e74-4ccd-973b-427714ff1bc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#title_brandsafe_video</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='title_brandsafe_video']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>91c2dd19-72ac-4e88-b986-8e7acf905785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>title_brandsafe_video</value>
      <webElementGuid>6c879d5c-405f-4341-b470-8bde59ac59b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>b74f35e7-eda1-48d5-9b28-66f431f91c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ngôi trường xây từ 80 nghìn viên sỏi</value>
      <webElementGuid>be3079a8-9e8a-47da-8aa1-0a291d70d80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title_brandsafe_video&quot;)</value>
      <webElementGuid>b9f1948f-c21c-41fa-a17b-e041a0c11f7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='title_brandsafe_video']</value>
      <webElementGuid>c34c01ac-121a-495c-9805-18466c3b78a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='info_inner']/h1</value>
      <webElementGuid>4fb519a2-cc05-4479-a28a-d8a1ba2825d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Âm lượng 50%'])[1]/following::h1[1]</value>
      <webElementGuid>1b5f5e74-f9ce-4b5b-a277-ebe1e566c458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close Modal Dialog'])[1]/following::h1[1]</value>
      <webElementGuid>f02f40a6-75f0-4331-b166-43ec9f2984d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sơn La'])[1]/preceding::h1[1]</value>
      <webElementGuid>1e97b8ee-892f-402c-8e48-a0cb2823f775</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lộc Chung - Anh Phú'])[1]/preceding::h1[1]</value>
      <webElementGuid>f71e15fa-dff6-4866-9178-68a69f66e044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ngôi trường xây từ 80 nghìn viên sỏi']/parent::*</value>
      <webElementGuid>8224fe08-05e0-4c2e-90a9-6671e2f79a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>c99692b1-c47f-487a-9d4c-2da50fc9cb45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'title_brandsafe_video' and (text() = 'Ngôi trường xây từ 80 nghìn viên sỏi' or . = 'Ngôi trường xây từ 80 nghìn viên sỏi')]</value>
      <webElementGuid>7c6cd4b3-c3bc-40b1-85d3-567711a48c7f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
