<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Video Player is loading_vjs-icon-placeholder</name>
   <tag></tag>
   <elementGuidId>32a3ad37-687c-4442-a706-45b682444d39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.vjs-icon-placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vne_vod']/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a88b4e85-391e-49df-94fa-4b4028550f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c28272b4-4aae-44f3-abe2-8399dfe891ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vjs-icon-placeholder</value>
      <webElementGuid>e5f8a25b-7d95-4753-89d3-335ec34f685d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vne_vod&quot;)/button[@class=&quot;vjs-big-play-button&quot;]/span[@class=&quot;vjs-icon-placeholder&quot;]</value>
      <webElementGuid>dc235e87-ded5-490c-b78e-7ef72a55e373</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vne_vod']/button/span</value>
      <webElementGuid>0d3c18d5-4a8d-4ab8-885b-fdb7992879a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>9b0d3f23-cd18-4f5f-9521-6168f8daf6bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
