<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ngi nh tng  cao 2 m bit lp trn ni cao</name>
   <tag></tag>
   <elementGuidId>b77df458-f03c-4c9b-82e1-9e382f6631d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='la_inner']/article[2]/h3/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>44b2c879-e7db-4c5b-a281-40b9283fb22e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-medium</name>
      <type>Main</type>
      <value>Item-2</value>
      <webElementGuid>3968f7a7-1538-4b43-a34c-ef4160480f67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-thumb</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b6cd2f6d-fddb-497d-970d-0346d79944fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://video.vnexpress.net/tin-tuc/nhip-song/ngoi-nha-tuong-da-cao-2-m-biet-lap-tren-nui-cao-4507074.html</value>
      <webElementGuid>19b70f6d-6cfe-4301-93d7-f097ddf1c9d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-category</name>
      <type>Main</type>
      <value>Video Folder Click</value>
      <webElementGuid>6d2041aa-eb9f-4ddd-a22f-8383eef64553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-action</name>
      <type>Main</type>
      <value>Box-InCategory</value>
      <webElementGuid>327bb861-6a7e-4ef6-82f8-c0cbb0a04125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-label</name>
      <type>Main</type>
      <value>Item-2</value>
      <webElementGuid>d3d200c8-9142-4c8f-9d17-32d3fe85fd07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>play_video</value>
      <webElementGuid>c2496187-e7f5-4c9e-b38e-a55f7a620793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ngôi nhà tường đá cao 2 m biệt lập trên núi cao</value>
      <webElementGuid>b2abfdd6-cf6c-41f9-aa88-2c9627be3fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itm-source</name>
      <type>Main</type>
      <value>#vn_source=Folder&amp;vn_campaign=Box-InCategory&amp;vn_medium=Item-2&amp;vn_term=Desktop&amp;vn_thumb=1&amp;vn_aid=1004075</value>
      <webElementGuid>5c184778-e0e8-41e1-825e-d8a68b1e9c8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ngôi nhà tường đá cao 2 m biệt lập trên núi cao</value>
      <webElementGuid>4e761fe8-fdc5-49c0-99d2-77b7641445d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;la_inner&quot;)/article[@class=&quot;art_item art_featured pel gaItemBoxDisplay init-preloaded&quot;]/h3[@class=&quot;title_news clearfix&quot;]/a[@class=&quot;play_video&quot;]</value>
      <webElementGuid>0ee655f6-ceb9-460e-bd53-692120ccbee9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='la_inner']/article[2]/h3/a</value>
      <webElementGuid>17b520a1-3fa4-4bab-b8b6-d2a08b1e86bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ngôi nhà tường đá cao 2 m biệt lập trên núi cao')]</value>
      <webElementGuid>130461c7-e230-46d8-b821-3fdafc760162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ám ảnh nhà vệ sinh của học trò vùng cao'])[1]/following::a[2]</value>
      <webElementGuid>0ffdb630-cc56-4b28-92ae-cf6ca441f1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cùng chuyên mục'])[1]/following::a[5]</value>
      <webElementGuid>f7f7da53-ccd4-4aac-9e52-238d583dfcb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngôi trường xây từ 80 nghìn viên sỏi'])[1]/preceding::a[2]</value>
      <webElementGuid>39b3e584-3988-4450-b66d-c814067bb25e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Cây ', &quot;'&quot;, 'cô đơn', &quot;'&quot;, ' hút hàng nghìn khách tham quan')])[1]/preceding::a[4]</value>
      <webElementGuid>13b19eda-e61a-430a-bc79-e9efcc9f531b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ngôi nhà tường đá cao 2 m biệt lập trên núi cao']/parent::*</value>
      <webElementGuid>50f00463-5820-4f34-ad1d-845f055497ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://video.vnexpress.net/tin-tuc/nhip-song/ngoi-nha-tuong-da-cao-2-m-biet-lap-tren-nui-cao-4507074.html')])[2]</value>
      <webElementGuid>c911876f-23ef-421f-8245-7627ccfd0c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[2]/h3/a</value>
      <webElementGuid>a9313d24-eb7a-44db-aba6-023d51b66dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://video.vnexpress.net/tin-tuc/nhip-song/ngoi-nha-tuong-da-cao-2-m-biet-lap-tren-nui-cao-4507074.html' and @title = 'Ngôi nhà tường đá cao 2 m biệt lập trên núi cao' and (text() = 'Ngôi nhà tường đá cao 2 m biệt lập trên núi cao' or . = 'Ngôi nhà tường đá cao 2 m biệt lập trên núi cao')]</value>
      <webElementGuid>a05da364-1c42-42ce-8e1d-4baf17318b3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
