<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Ph lng n TP HCM tp np khch</name>
   <tag></tag>
   <elementGuidId>feb1e694-2f81-4efd-817b-b03993303327</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#title_brandsafe_video</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='title_brandsafe_video']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>7965b8f0-b1d5-43ed-97db-bc9791d5c743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>title_brandsafe_video</value>
      <webElementGuid>046ce8d6-09a8-43c5-9d5a-eaed08b9f916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>56ab7594-bf69-426d-8d52-febed24607a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Phố lồng đèn TP HCM tấp nập khách</value>
      <webElementGuid>2f0d176d-3eab-436b-969c-2bce64bbc2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;title_brandsafe_video&quot;)</value>
      <webElementGuid>26e0b3c7-dd90-49d8-af98-8ef628611e9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='title_brandsafe_video']</value>
      <webElementGuid>ea16a188-7abe-44f8-920b-11295e4e64f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='info_inner']/h1</value>
      <webElementGuid>134c0241-a438-4831-82c7-6e275be28bcb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Âm lượng 50%'])[1]/following::h1[1]</value>
      <webElementGuid>49173305-6d1f-4ef6-ab9d-3a9eae38bd92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close Modal Dialog'])[1]/following::h1[1]</value>
      <webElementGuid>ca6e83f6-b966-4c97-8d57-f460b2da511e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Công Khang'])[1]/preceding::h1[1]</value>
      <webElementGuid>665e357a-3a3b-4971-bbb8-77d09cf64908</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='video@vnexpress.net'])[1]/preceding::h1[1]</value>
      <webElementGuid>a5f3d081-914f-4712-b129-5bfe7b86c4c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Phố lồng đèn TP HCM tấp nập khách']/parent::*</value>
      <webElementGuid>1ef91e48-bce8-4e10-b1e1-819c5d9ef9d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>77e91ee0-a166-470b-a294-6da507be06ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'title_brandsafe_video' and (text() = 'Phố lồng đèn TP HCM tấp nập khách' or . = 'Phố lồng đèn TP HCM tấp nập khách')]</value>
      <webElementGuid>4f2e85a8-8435-4c6c-8178-4abf1f8f2a94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
