<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yuyu</name>
   <tag></tag>
   <elementGuidId>07389e19-2bd7-4cf8-9170-57da8b151d92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='ac-globalnav']/div/ul[2]/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed748ef6-0a58-497d-9b76-ff4de65b94d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ac-gn-link ac-gn-link-watch </value>
      <webElementGuid>a55cb289-d37f-452b-ad9b-12d17356cc89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.apple.com/watch/</value>
      <webElementGuid>662decc5-c03b-4270-a2a3-827ae0e8c2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-analytics-title</name>
      <type>Main</type>
      <value>watch</value>
      <webElementGuid>f29df95a-50f4-4e4d-ac1e-58aa038e31a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-feature-name</name>
      <type>Main</type>
      <value>Globalnav</value>
      <webElementGuid>f8c959e6-3d4a-4a9c-8953-d1dc2abb5db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-display-name</name>
      <type>Main</type>
      <value>watch</value>
      <webElementGuid>cb2bf6c4-2bfe-4ce2-ab11-ecdf02f7c816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-focus-method</name>
      <type>Main</type>
      <value>mouse</value>
      <webElementGuid>b263cc91-f3f2-4e77-974a-912e58d96e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					Watch
				</value>
      <webElementGuid>736dfb68-ca83-41b8-8354-8b00f15e210f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ac-globalnav&quot;)/div[@class=&quot;ac-gn-content&quot;]/ul[@class=&quot;ac-gn-list&quot;]/li[@class=&quot;ac-gn-item ac-gn-item-menu ac-gn-watch&quot;]/a[@class=&quot;ac-gn-link ac-gn-link-watch&quot;]</value>
      <webElementGuid>1c10f545-0a90-4ba6-86a1-8e810bf1c772</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='ac-globalnav']/div/ul[2]/li[6]/a</value>
      <webElementGuid>a7a053cb-9c78-48e6-8790-f30bf8a9c8d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iPhone'])[1]/following::a[1]</value>
      <webElementGuid>ba746a09-2ef5-4d6e-b889-ff6cb9996d96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iPad'])[1]/following::a[2]</value>
      <webElementGuid>684b89d6-7ed4-4471-9b66-cd221eac972d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AirPods'])[1]/preceding::a[1]</value>
      <webElementGuid>adfb1fa8-255e-4e2b-b425-d9740f97ce5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.apple.com/watch/')]</value>
      <webElementGuid>3b62bd72-41ef-4fa6-bad0-b39fdc08b545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>a0245075-97ab-46bd-bd97-a08fdd11aae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.apple.com/watch/' and (text() = '
					Watch
				' or . = '
					Watch
				')]</value>
      <webElementGuid>57b926e7-9e95-4fa2-84c3-070c37cc2d54</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
