<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Video</name>
   <tag></tag>
   <elementGuidId>5f591ae6-6b93-4451-acd5-c6d218f71547</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Video&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='wrap-main-nav']/nav/ul/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>af178326-a7d3-4870-90c2-c5f6616669e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Video</value>
      <webElementGuid>dea81103-f467-4739-ae16-95d9a232ece9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://video.vnexpress.net</value>
      <webElementGuid>23ae01c3-bab0-4930-a188-507b61c12b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-medium</name>
      <type>Main</type>
      <value>Menu-Video</value>
      <webElementGuid>a58808dc-40e2-46aa-8972-311aa1843563</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itm-source</name>
      <type>Main</type>
      <value>#vn_source=Folder-GocNhin&amp;vn_campaign=Header&amp;vn_medium=Menu-Video&amp;vn_term=Desktop</value>
      <webElementGuid>849c1239-adf0-49d9-9c79-497537a1071a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itm-added</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>35a80ba0-c508-48ad-bdd7-18ffad3f2c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Video </value>
      <webElementGuid>88ceb870-40a3-4a74-8da6-2abf974716bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrap-main-nav&quot;)/nav[@class=&quot;main-nav&quot;]/ul[@class=&quot;parent&quot;]/li[@class=&quot;video&quot;]/a[1]</value>
      <webElementGuid>b96cc58b-932a-4bb6-8018-1e691339f5d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='wrap-main-nav']/nav/ul/li[6]/a</value>
      <webElementGuid>b1c027fc-bf4b-4973-9ec8-7ef407645d22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Video')]</value>
      <webElementGuid>378cf4f3-e5e8-4b4b-9018-941e2d39b055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quân sự'])[1]/following::a[1]</value>
      <webElementGuid>35d332d4-ff0b-452c-ad9c-c0e7174841fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuộc sống đó đây'])[1]/following::a[2]</value>
      <webElementGuid>24d8da81-1b11-40a3-9946-47de8328e63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thời sự'])[2]/preceding::a[1]</value>
      <webElementGuid>2e6bb1e3-f29b-4dcb-86bd-4a0637c8a4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nhịp sống'])[1]/preceding::a[2]</value>
      <webElementGuid>e116a9d0-2dd8-4424-8869-4c1ae4a6c8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Video']/parent::*</value>
      <webElementGuid>d3adb64e-f57f-4405-a588-23d484d49251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://video.vnexpress.net')]</value>
      <webElementGuid>bb56281b-6988-4db6-a9cf-6052dfe88144</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>21b47ee8-f601-4337-ba67-f241b00f29ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Video' and @href = 'https://video.vnexpress.net' and (text() = '
Video ' or . = '
Video ')]</value>
      <webElementGuid>31a09106-2197-421c-b981-1316811645be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
