<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Video_1</name>
   <tag></tag>
   <elementGuidId>e579413d-0cca-49d0-a4e8-2a727cb89f97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Video&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='wrap-main-nav']/nav/ul/li[6]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1d78c8d2-d3d9-4d54-9ca5-1aceefaa4801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Video</value>
      <webElementGuid>b8c8974b-14ed-4360-ac76-11fdaf0b1d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://video.vnexpress.net/#vn_source=Folder-GocNhin&amp;vn_campaign=Header&amp;vn_medium=Menu-Video&amp;vn_term=Desktop&amp;vn_aid=1003450&amp;vn_aid=1003450</value>
      <webElementGuid>6fbe4ef8-c0d3-4c28-a6bb-65fa48f80c9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-medium</name>
      <type>Main</type>
      <value>Menu-Video</value>
      <webElementGuid>b8089b65-7744-430a-8b7c-59af573cdc36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itm-source</name>
      <type>Main</type>
      <value>#vn_source=Folder-GocNhin&amp;vn_campaign=Header&amp;vn_medium=Menu-Video&amp;vn_term=Desktop</value>
      <webElementGuid>b23b02fb-c9e7-49bb-b518-b26bf5862f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itm-added</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1d3b31af-8b8b-40da-aca1-8bc1800831b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Video </value>
      <webElementGuid>0fe46997-b708-4d70-90d0-d4b820400eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrap-main-nav&quot;)/nav[@class=&quot;main-nav&quot;]/ul[@class=&quot;parent&quot;]/li[@class=&quot;video&quot;]/a[1]</value>
      <webElementGuid>5242a995-77d6-4728-9106-308f72e1fbbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='wrap-main-nav']/nav/ul/li[6]/a</value>
      <webElementGuid>09c13352-c5f0-4c12-bb0f-e6f285641a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Video')]</value>
      <webElementGuid>51d731cb-930b-4ced-a2c0-2a8bee20f31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quân sự'])[1]/following::a[1]</value>
      <webElementGuid>7e157134-fe11-4534-ba36-47daaa12a12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuộc sống đó đây'])[1]/following::a[2]</value>
      <webElementGuid>9f8c12ce-3454-4a17-9eea-932007a1cb5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thời sự'])[2]/preceding::a[1]</value>
      <webElementGuid>d22f2dcc-b583-4ebc-a438-1c9d7270aba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nhịp sống'])[1]/preceding::a[2]</value>
      <webElementGuid>c5a21247-c084-44ee-b2a3-8b1c6207d278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Video']/parent::*</value>
      <webElementGuid>5aa4c6ec-98c4-4b8f-bdac-a528373dd266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://video.vnexpress.net/#vn_source=Folder-GocNhin&amp;vn_campaign=Header&amp;vn_medium=Menu-Video&amp;vn_term=Desktop&amp;vn_aid=1003450&amp;vn_aid=1003450')]</value>
      <webElementGuid>2d3311fd-e118-416b-ad83-de0c85072f73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/a</value>
      <webElementGuid>0034f234-c888-4c0e-bfb5-a5a61b30629a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Video' and @href = 'https://video.vnexpress.net/#vn_source=Folder-GocNhin&amp;vn_campaign=Header&amp;vn_medium=Menu-Video&amp;vn_term=Desktop&amp;vn_aid=1003450&amp;vn_aid=1003450' and (text() = '
Video ' or . = '
Video ')]</value>
      <webElementGuid>ed3d5dd8-efc5-4e94-9c12-270ab95dcd4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
