<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Gc nhn_1</name>
   <tag></tag>
   <elementGuidId>f0ff1cc6-c5a2-47d8-87dd-fe86291a115e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Góc nhìn&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='wrap-main-nav']/nav/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5aec2e5e-59f5-457c-80c4-c5db15726f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Góc nhìn</value>
      <webElementGuid>b3a4633b-e1da-4cf6-b1b3-8d6085b5708b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://vnexpress.net/goc-nhin#vn_source=Detail-ThoiSu_DanSinh-4508908&amp;vn_campaign=Pinbar&amp;vn_medium=Menu-GocNhin&amp;vn_term=Desktop&amp;vn_aid=4508908&amp;vn_aid=4508908</value>
      <webElementGuid>7f7e366a-a8f0-4747-bb49-f7cff1e3d456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-medium</name>
      <type>Main</type>
      <value>Menu-GocNhin</value>
      <webElementGuid>9a8a80a5-3c4d-4569-b6fd-d1eba1082ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itm-source</name>
      <type>Main</type>
      <value>#vn_source=Detail-ThoiSu_DanSinh-4508908&amp;vn_campaign=Pinbar&amp;vn_medium=Menu-GocNhin&amp;vn_term=Desktop</value>
      <webElementGuid>388733a8-ca0b-4c24-9256-0e5370c006d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itm-added</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>87306626-c810-4223-a476-aaf6c987fd90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Góc nhìn </value>
      <webElementGuid>efe0cc4f-78f2-4cfc-8ead-fd9d8cb24fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrap-main-nav&quot;)/nav[@class=&quot;main-nav&quot;]/ul[@class=&quot;parent&quot;]/li[@class=&quot;gocnhin&quot;]/a[1]</value>
      <webElementGuid>60063e63-0ded-4735-a936-e9e94df6e2fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='wrap-main-nav']/nav/ul/li[4]/a</value>
      <webElementGuid>68cf3a14-eee8-4e43-bc71-306a8c7d217f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Góc nhìn')]</value>
      <webElementGuid>61d26d62-138d-4e17-b3c0-3fbf8b0918f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quỹ Hy vọng'])[1]/following::a[1]</value>
      <webElementGuid>6f2fc9ad-fdf6-4c75-b252-2e35da10496c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mekong'])[1]/following::a[2]</value>
      <webElementGuid>10638067-3f95-49e4-97a4-230c0acf0dff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bình luận nhiều'])[1]/preceding::a[1]</value>
      <webElementGuid>23d283a2-2434-4451-8630-a0921eb87893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chính trị &amp; chính sách'])[1]/preceding::a[2]</value>
      <webElementGuid>28edfa59-6f99-42ea-a69e-99c63cb84107</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Góc nhìn']/parent::*</value>
      <webElementGuid>3ba7c8a6-e077-41cc-a47a-f81e72bf3b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://vnexpress.net/goc-nhin#vn_source=Detail-ThoiSu_DanSinh-4508908&amp;vn_campaign=Pinbar&amp;vn_medium=Menu-GocNhin&amp;vn_term=Desktop&amp;vn_aid=4508908&amp;vn_aid=4508908')]</value>
      <webElementGuid>9fd99f5d-7d0a-4d7a-a203-f1d035279aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a</value>
      <webElementGuid>9780bdbb-b5b5-4675-a073-96e1450d29da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Góc nhìn' and @href = 'https://vnexpress.net/goc-nhin#vn_source=Detail-ThoiSu_DanSinh-4508908&amp;vn_campaign=Pinbar&amp;vn_medium=Menu-GocNhin&amp;vn_term=Desktop&amp;vn_aid=4508908&amp;vn_aid=4508908' and (text() = '
Góc nhìn ' or . = '
Góc nhìn ')]</value>
      <webElementGuid>0905f4ba-891f-465a-8136-f2f64476a3f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
