<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ngi trng xy t 80 nghn vin si</name>
   <tag></tag>
   <elementGuidId>0323f9e9-b216-4e2a-856c-2dcc0a31451e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='la_inner']/article[2]/h3/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2a41d1cc-5ed6-48b6-bb91-b4a94aa6085e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-medium</name>
      <type>Main</type>
      <value>Item-2</value>
      <webElementGuid>28aa9de9-a6c4-432c-b864-9906003b31d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-thumb</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>89199021-028f-4bca-a44c-f8609a0e2b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://video.vnexpress.net/tin-tuc/nhip-song/ngoi-truong-xay-tu-80-nghin-vien-soi-4507055.html</value>
      <webElementGuid>94b7dc00-fa64-4f95-9009-314caf9a4764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-category</name>
      <type>Main</type>
      <value>Video Detail Click</value>
      <webElementGuid>8c00ddc8-af0d-449a-aa4d-28ad340e4f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-action</name>
      <type>Main</type>
      <value>Box-InCategory</value>
      <webElementGuid>afdd229b-a913-44f5-8140-cdfea75d3e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-event-label</name>
      <type>Main</type>
      <value>Item-2</value>
      <webElementGuid>68fbcfc7-51ee-4030-b7a3-3ea4df4da893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>play_video</value>
      <webElementGuid>9ed80582-0dc1-4bdc-b77f-3c8906026135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ngôi trường xây từ 80 nghìn viên sỏi</value>
      <webElementGuid>81cd275e-536d-4a99-922e-b966af7e1fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-itm-source</name>
      <type>Main</type>
      <value>#vn_source=Detail&amp;vn_campaign=Box-InCategory&amp;vn_medium=Item-2&amp;vn_term=Desktop&amp;vn_thumb=1&amp;vn_aid=4507074</value>
      <webElementGuid>5b0b1803-03ad-43ee-8dfb-8d60308a0954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ngôi trường xây từ 80 nghìn viên sỏi</value>
      <webElementGuid>cc673e8b-0178-4eef-abd9-f2d5e447b250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;la_inner&quot;)/article[@class=&quot;art_item art_featured pel gaItemBoxDisplay init-preloaded&quot;]/h3[@class=&quot;title_news clearfix&quot;]/a[@class=&quot;play_video&quot;]</value>
      <webElementGuid>5f3ce982-cefd-47b6-8a2f-3b01839889ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='la_inner']/article[2]/h3/a</value>
      <webElementGuid>afd510cd-4969-4149-b52b-2b690f48eb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ngôi trường xây từ 80 nghìn viên sỏi')]</value>
      <webElementGuid>9d3bcf9e-c6b7-45a5-a1a9-7bcaaa7111ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ám ảnh nhà vệ sinh của học trò vùng cao'])[1]/following::a[2]</value>
      <webElementGuid>ba096867-1ad2-4579-8912-1bff367b73a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cùng chuyên mục'])[1]/following::a[5]</value>
      <webElementGuid>4e346e67-d8c0-489b-95ff-1135fd0301b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Cây ', &quot;'&quot;, 'cô đơn', &quot;'&quot;, ' hút hàng nghìn khách tham quan')])[1]/preceding::a[2]</value>
      <webElementGuid>85923aeb-c402-44fd-858a-074d4f31e064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phú Mỹ Hưng lần đầu xây khu căn hộ tại Hồ Bán Nguyệt'])[1]/preceding::a[4]</value>
      <webElementGuid>eb3150c9-2e20-4219-a1ec-231c4d797c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ngôi trường xây từ 80 nghìn viên sỏi']/parent::*</value>
      <webElementGuid>a7a47052-7b25-409a-b6b2-e754c9e1f2f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://video.vnexpress.net/tin-tuc/nhip-song/ngoi-truong-xay-tu-80-nghin-vien-soi-4507055.html')])[3]</value>
      <webElementGuid>385c41d3-4677-4029-bdb9-e74c7c141e6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article[2]/h3/a</value>
      <webElementGuid>a5e54b89-adf4-4b82-bbe6-44dd9348257a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://video.vnexpress.net/tin-tuc/nhip-song/ngoi-truong-xay-tu-80-nghin-vien-soi-4507055.html' and @title = 'Ngôi trường xây từ 80 nghìn viên sỏi' and (text() = 'Ngôi trường xây từ 80 nghìn viên sỏi' or . = 'Ngôi trường xây từ 80 nghìn viên sỏi')]</value>
      <webElementGuid>a7c4f05d-d367-45e0-a2d3-55347b877115</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
