<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Video Player is loading_vjs-icon-placeholder</name>
   <tag></tag>
   <elementGuidId>680193ad-7a97-482a-8a4c-6b584751cc5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.vjs-icon-placeholder</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='vne_vod']/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1e0457e0-ca4b-42c9-ae9e-39be44cff058</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>64318f28-ffcd-4b9b-ab18-a9aed1e6f5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>vjs-icon-placeholder</value>
      <webElementGuid>49e84291-2e52-4bdc-8431-ee91554c642e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;vne_vod&quot;)/button[@class=&quot;vjs-big-play-button&quot;]/span[@class=&quot;vjs-icon-placeholder&quot;]</value>
      <webElementGuid>581aa085-7aaa-42dd-9f20-e326e806608b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vne_vod']/button/span</value>
      <webElementGuid>a05c8899-f9d0-4337-8681-4fec696f6a1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>22568391-2bc9-4aef-9084-42ea83a71613</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
