<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_Video_ic ic-menu</name>
   <tag></tag>
   <elementGuidId>ff7c2030-eff9-403f-8316-368aac089362</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.ic.ic-menu</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//header[@id='header']/div/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8b259f12-d1a2-4ad9-8242-67c7574d9fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ic ic-menu</value>
      <webElementGuid>480f339a-57ad-4067-817b-8528851e2678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;header&quot;)/div[@class=&quot;btn_control_menu&quot;]/i[@class=&quot;ic ic-menu&quot;]</value>
      <webElementGuid>693a5bad-0b7b-433d-ab79-ab0678d0c763</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/i</value>
      <webElementGuid>a123ca83-a86c-4158-9286-30faeb411b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>487161a9-8b19-461d-ab53-4bff63fdf9d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
